services:
  - type: web
    name: sistema-inventario
    runtime: docker
    region: oregon        # cambia si prefieres otra región; DB y web deben estar en la misma región
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_DATASOURCE_HOST
        fromDatabase:
          name: sistema-inventario-db
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromDatabase:
          name: sistema-inventario-db
          property: port
      - key: SPRING_DATASOURCE_DB
        fromDatabase:
          name: sistema-inventario-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sistema-inventario-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sistema-inventario-db
          property: password

      # Mail: se solicitarán al aplicar el Blueprint (no guardes aquí valores en texto plano)
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false

databases:
  - name: sistema-inventario-db
    region: oregon
    plan: free
